language: [php, node_js]

node_js: ['0.10']

php: [5.4, 5.5, 5.6]

before_install:
  - npm install -g bower
  - npm install -g grunt-cli

install:
  - npm install
  - bower install --config.interactive=false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - bin/phpspec run
  - grunt
