language: [php]

php: [5.4, 5.5, 5.6]

before_script:
  - cp client/config/config.json.dist client/config/config.json
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpspec run
