---
- name: copy source.list
  copy: src=sources.list dest=/etc/apt/sources.list

- name: apt | dist-upgrade
  apt: upgrade=dist update_cache=yes cache_valid_time=86400 force=yes

- name: common dependencies
  apt: pkg={{ item }}
  with_items:
    - git
    - vim
    - curl
    - apt-transport-https

- name: set locales
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
    - fr_FR.UTF-8
