account:
  type:     rest
  resource: OhMyBank\Bundle\ApiBundle\Controller\AccountController

ohmybank_index:
    pattern:  /{path}
    requirements:
        path: "^(?!(api|assets)/).*"
    defaults:
        _controller: FrameworkBundle:Template:template
        template: ::index.html.twig
        path: ~
