---

- name: Add dotdeb keys
  apt_key:
    url=http://www.dotdeb.org/dotdeb.gpg
    state=present

- name: Add dotdeb repo for php 5.5
  apt_repository: repo='deb http://packages.dotdeb.org wheezy-php55 all' state=present

- name: Add dotdeb repo
  apt_repository: repo='deb http://packages.dotdeb.org wheezy all' update_cache=yes state=present

- name: apt | install php 5.5
  apt: pkg={{ item }}
  with_items:
    - php5
    - php5-cli
    - php5-fpm
    - php5-mcrypt
    - php5-dev
    - php5-curl
    - php5-mcrypt
    - php5-xdebug
    - php5-mysql
    - php5-intl
    - php5-tidy
